name: Update the bcd version

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 6'    # Run at 00:00 UTC every Saturday

permissions:
  contents: write
  issues: write

jobs:
  update_bcd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Update version
        run: |
          python tools/update_bcd_version.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bcd_version
          git diff --quiet && git diff --staged --quiet || git commit -m "Update bcd version"
          git push
      - name: Notify failed build
        uses: jayqi/failed-build-issue-action@v1
        if: failure() && github.event.pull_request == null
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title-template: "BCD version update failed"
          body-template: | 
            The BCD version update has failed check for new major versions and update manually.
            
            Please check the [logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
