name: Update the bcd version

on:
  workflow_dispatch:

  schedule:
    - cron: '30 14 * * *'    # Test run at 14:30 UTC

permissions:
  contents: write

jobs:
  update bcd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Update version
        run: |
          python tools/update_bcd_version.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bcd_version
          git diff --quiet && git diff --staged --quiet || git commit -m "Update bcd version"
          git push
